sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
build:
  runnerOs: ubuntu-20.04
  exasolDbVersions:
    - "7.1.24"
#    - "8.23.1" disabled due to failing tests
