sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
linkReplacements:
  - https://www.microsoft.com/en-us/sql-server/sql-server-2017|https://www.microsoft.com/en-us/sql-server
